// <auto-generated />
using System;
using DooHAdvertAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DooHAdvertAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230702210937_firstSeededMigrationDatabase")]
    partial class firstSeededMigrationDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DooHAdvertAPI.Models.Adverts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            EndTime = new DateTime(2023, 7, 6, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/AeroTech Drones",
                            Priority = 9,
                            StartTime = new DateTime(2023, 7, 2, 22, 9, 37, 233, DateTimeKind.Local).AddTicks(7745)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 3,
                            EndTime = new DateTime(2023, 7, 8, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/HumblePies",
                            Priority = 4,
                            StartTime = new DateTime(2023, 7, 2, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            EndTime = new DateTime(2023, 7, 8, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/Java Coffee",
                            Priority = 6,
                            StartTime = new DateTime(2023, 7, 3, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            EndTime = new DateTime(2023, 7, 9, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/LNN",
                            Priority = 6,
                            StartTime = new DateTime(2023, 7, 4, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            EndTime = new DateTime(2023, 7, 10, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/LumoThread",
                            Priority = 2,
                            StartTime = new DateTime(2023, 7, 5, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            EndTime = new DateTime(2023, 7, 11, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/MackyCs",
                            Priority = 5,
                            StartTime = new DateTime(2023, 7, 6, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            EndTime = new DateTime(2023, 7, 11, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/Solaris Solar",
                            Priority = 2,
                            StartTime = new DateTime(2023, 7, 6, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            EndTime = new DateTime(2023, 7, 11, 5, 10, 0, 0, DateTimeKind.Unspecified),
                            Path = "Resources/Images/Solaris Solar",
                            Priority = 9,
                            StartTime = new DateTime(2023, 7, 2, 22, 9, 37, 233, DateTimeKind.Local).AddTicks(7813)
                        });
                });

            modelBuilder.Entity("DooHAdvertAPI.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bournemouth"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sheffield"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Leeds"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Brighton"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hove"
                        });
                });

            modelBuilder.Entity("DooHAdvertAPI.Models.Adverts", b =>
                {
                    b.HasOne("DooHAdvertAPI.Models.Location", "City")
                        .WithMany("Adverts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DooHAdvertAPI.Models.Location", b =>
                {
                    b.Navigation("Adverts");
                });
#pragma warning restore 612, 618
        }
    }
}
